* Categorization numbers changed:

country_flag

US_ONLY         19255 --> 11120

BOTH            16661 --> 24796

FOREIGN_ONLY     2634 --> 3213

NONE             2598 --> 2019

In [1]:
import pandas as pd
df_articles = pd.read_pickle("../../data/processed/cleaned_articles.pkl")

In [2]:
df_articles.shape

(41148, 14)

In [3]:
df_articles.head()

,title,publisher,date,section,body,length,letters_flag,country_flag,foreign_countries,us_mentions,source_file,publisher_raw,section_clean,section_category
0,A Well-Documented Childhood. A Very Private Life.,New York Times,2024-12-31,Section A; Column 0; National Desk; Pg. 16,Jimmy Carter's daughter had an extraordinary a...,1209,False,BOTH,"[Canada, Egypt, Mexico, Nicaragua, Washington ...","[Massachusetts, Rhode Island, US, Washington]",NYT/1.DOCX,The New York Times,section a; column 0; national desk; pg. 16,US/National
1,These were the big stories in arts and culture...,Other publisher,2024-12-31,WHAT TO KNOW,The arts in Dayton continued to thrive in 2024...,3345,False,BOTH,"[France, Japan, Paris (Capital), Sierra Leone,...","[America, California, Florida, Georgia, Massac...",Other publishers/Files (500) (1).DOCX,Dayton Daily News (Ohio),what to know,None
2,She Exalted The Beauty Of Dance,New York Times,2024-12-31,Section C; Column 0; The Arts/Cultural Desk; P...,She was The New Yorker's first dance critic. H...,1314,False,BOTH,[Male (Capital)],"[New York, North Carolina, US, United States]",NYT/1.DOCX,The New York Times,section c; column 0; the arts/cultural desk; p...,Arts/Culture
3,"Under a Highway in Rio, a Dance Style Charms a...",New York Times,2024-12-31,WORLD; americas,"Trucks, buses and cars rumbled overhead, drown...",1333,False,BOTH,"[Brazil, Lima (Capital)]","[New York, US, United States]",NYT/1.DOCX,The New York Times,world; americas,World/International
4,"Congressional pay, minimum wage stagnant for y...",Other publisher,2024-12-31,OPINION; Pg. A13,ABSTRACT\nMembers of Congress have not seen a ...,921,False,US_ONLY,[],"[America, Delaware, Maryland, New Jersey, New ...",Other publishers/Files (500) (1).DOCX,The Philadelphia Inquirer,opinion; pg. a13,Opinion/Editorial/Letters

In [4]:
df_articles.section_category.fillna(value="None", inplace=True)

/var/folders/r0/7r973sr56n5dr64wkq37dk8r0000gn/T/ipykernel_8293/935527085.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_articles.section_category.fillna(value="None", inplace=True)

In [5]:
df_articles['section_category'].value_counts()

section_category
US/National                  6235
Arts/Culture                 6103
None                         5797
Opinion/Editorial/Letters    5449
Metro/Local                  5379
Style/Life/Fashion           4308
World/International          3269
Business/Finance             1935
books/podcast                1702
Sports                        894
Science/Health/Tech            77
Name: count, dtype: int64

In [16]:
import pandas as pd

counts = pd.crosstab(df_articles['section_category'], df_articles['country_flag']).reset_index()
print(counts)

country_flag           section_category  BOTH  FOREIGN_ONLY  NONE  US_ONLY
0                          Arts/Culture  3791           667   416     1229
1                      Business/Finance  1174            79    79      603
2                           Metro/Local  2622           177   417     2163
3                                  None  3167           283   368     1979
4             Opinion/Editorial/Letters  3176           217   310     1746
5                   Science/Health/Tech    60             3     1       13
6                                Sports   539            61    33      261
7                    Style/Life/Fashion  2816           369   201      922
8                           US/National  4180           105   120     1830
9                   World/International  2048          1158    22       41
10                        books/podcast  1223            94    52      333

relevant_to_me:

* If Arts/Culture, Business/Finance, None, Opinion/Editorial/Letters, Science/Health/Tech, Sports, books/podcastStyle/Life/Fashion: 
    US_ONLY, BOTH, NONE
* All Metro/Local, US/National
* Exclude World/International

In [17]:
domestic_categories = ['US/National', 'Metro/Local']

domestic_categories_secondary = ['Arts/Culture', 'Business/Finance', 'Opinion/Editorial/Letters',
                       'Science/Health/Tech', 'Sports', 'Style/Life/Fashion', 'books/podcast']

world_categories = ['World/International']

In [18]:
section_category_selection = "US/National"
country_flag_selection = "FOREIGN_ONLY"

df_select = df_articles.loc[(df_articles['section_category'] == section_category_selection) & (df_articles['country_flag'] == country_flag_selection)]
print(f"Number of articles in selection: {df_select.shape[0]} ({round(df_select.shape[0] / df_articles.shape[0] * 100, 2)}% of total articles)")

print("Examples:")
# examples
df_select.head(2)

Number of articles in selection: 105 (0.26% of total articles)
Examples:

,title,publisher,date,section,body,length,letters_flag,country_flag,foreign_countries,us_mentions,source_file,publisher_raw,section_clean,section_category
963,U.A.W. Files Labor Charges Against Trump and M...,New York Times,2024-08-13,US; politics,The United Automobile Workers union accused th...,486,False,FOREIGN_ONLY,[France],[],NYT/1.DOCX,The New York Times,us; politics,US/National
1654,A Close-Up View of the Baltimore Bridge Collapse,New York Times,2024-03-30,US,"From roughly 100 yards away, the site of one o...",712,False,FOREIGN_ONLY,"[El Salvador, Guatemala, Honduras, India]",[],NYT/3.DOCX,The New York Times,us,US/National

In [6]:
section_category_selection = "Metro/Local"
country_flag_selection = "FOREIGN_ONLY"

df_select = df_articles.loc[(df_articles['section_category'] == section_category_selection) & (df_articles['country_flag'] == country_flag_selection)]
print(f"Number of articles in selection: {df_select.shape[0]} ({round(df_select.shape[0] / df_articles.shape[0] * 100, 2)}% of total articles)")

print("Examples:")
# examples
df_select.head(2)

Number of articles in selection: 177 (0.43% of total articles)
Examples:

,title,publisher,date,section,body,length,letters_flag,country_flag,foreign_countries,us_mentions,source_file,publisher_raw,section_clean,section_category
1708,INNAMORATO DELIVERS FIRST QUARTERLY ADDRESS; C...,Other publisher,2024-03-20,LOCAL; Pg. A-9,In her first quarterly address to the Alleghen...,752,False,FOREIGN_ONLY,[Israel],[],Other publishers/Files (500) (1).DOCX,Pittsburgh Post-Gazette,local; pg. a-9,Metro/Local
1871,Mayor's assistant doubling as driver,Other publisher,2024-02-05,REGION; Pg. B2,As new Mayor Cherelle L. Parker gets settled i...,887,False,FOREIGN_ONLY,[Hamilton (Capital)],[],Other publishers/Files (500) (2).DOCX,The Philadelphia Inquirer,region; pg. b2,Metro/Local

In [8]:
df_select.iloc[0]['title']

"INNAMORATO DELIVERS FIRST QUARTERLY ADDRESS; COUNTY EXEC TOUTS ADMINISTRATION'S ACCOMPLISHMENTS"

In [9]:
df_select.iloc[0]['body']

'In her first quarterly address to the Allegheny County Council, county Executive Sara Innamorato shed light on the direction of her administration and its accomplishments as she nears her first 100 days in office.\nDuring the 40-minute address at the top of Tuesday\'s council meeting, Ms. Innamorato touted her administration\'s expansion of affordable childcare, pay raises for non-union county workers, and an improved public safety communications system.\nShe also highlighted her collaborative work with the council to pass the Local Economic Revitalization Assistance (LERTA) Act in February, a tax abatement program that will incentivize new development downtown and convert underused office spaces in the city center to affordable housing units.\nDrilling down on her economic agenda, Ms. Innamorato pointed to the "hundreds of new jobs" the recent move by Boston-based company Excelitas Technologies to Pittsburgh\'s Strip District will create, but said there is still much more work to be done if the county wants to sustain long-term growth.\n"Comprehensive economic development, it moves beyond these traditional tools we look at when we talk about economic development… It\'s about investing in social safety nets, it\'s about helping working families," Ms. Innamorato said.\nInvestments in social services, like affordable childcare and housing, has been a pillar of the administration\'s economic approach, she said. In early January, Innamorato pushed for additional funding for the Allegheny Childcare Matters Program, which provides low-income families with childcare access.\nThe county approved $500,000 in American Rescue Plan funds to be invested in the program, which Innamorato said Tuesday cleared the path for a backlog of applicants to receive benefits.\n"This investment represents the importance to my administration of the efforts of supporting working-class families," she said. She also pointed to Department of Human Services efforts to expand shelter for the unhoused population and create a program for opioid use disorder.\nPrompted by a question from councilmember at-large Bethany Hallam about the clearing of unhoused encampments and new shelter options, Ms. Innamorato said the county is "missing" the capacity for people who don\'t meet subsidized housing requirements or who have spent years on housing choice voucher waitlists.\nExpanding shelter options for that group is a priority, she said. Responding to a question about the county jail, Ms. Innamorato said a report summarizing stakeholder input on its redesign will become public soon.\nThe redesign report will contain input from current and formerly incarcerated individuals, elected officials and community members.\nDan Grzybek, representative for council district 5, asked about air quality, pointing to record numbers of hydrogen sulfide exceedances.\n"We are laser-focused on finding our next health director," Ms. Innamorato responded. To help in the search, the administration has hired an external consulting firm, which plans to schedule "over 100" meetings to collect public input.\nFinding a new warden for the county jail is also a top priority in the coming months, Ms. Innamorato said; she appointed three citizen members to the jail oversight board in January.\nMs. Innamorato answered council-member questions on topics that spanned from the continuation of benefits for communities affected by the 2018 Clairton Coke Works fire, which expire in June 2024, to her plan for the shuttered Shuman Juvenile Detention Center.\nxMs. Innamorato touched on efforts to implement five new ballot drop-off locations across the county ahead of the primary election, but did not address a lawsuit from councilmember Sam DeMarco that questioned her authority to do so. A judge ruled earlier in the day that Mr. DeMarco was correct. The election board, of which Mr. DeMarco is a member, will put the matter to a final vote Wednesday.\nThe council voted to approve Ms. Innamorato\'s second slate of board appointees and conducted second readings of two bills currently in Budget and Finance Committee review before opening the floor for a heated period of public comment.\nMore than 10 people gave emotionally charged speeches in response to the council\'s decision to vote down a resolution calling for a ceasefire in the Israel-Hamas war that would have called on the Biden administration to end all violence in the region.\nPublic comment and discussion on the matter will likely be added to the agenda for the council\'s next meeting, Ms. Hallam said.\n\nGraphic\n\n \nPHOTO: Tim Robbibaro/For the Post-Gazette: Sara Innamorato County Executive and Board Member of the Allegheny County Jail Oversight Board at the monthly Jail oversight meeting on Thursday, Jan. 4, 2024 at the Allegheny County Courthouse Downtown.'

In [20]:
section_category_selection = "World/International"
country_flag_selection = "US_ONLY"

df_select = df_articles.loc[(df_articles['section_category'] == section_category_selection) & (df_articles['country_flag'] == country_flag_selection)]
print(f"Number of articles in selection: {df_select.shape[0]} ({round(df_select.shape[0] / df_articles.shape[0] * 100, 2)}% of total articles)")

print("Examples:")
# examples
df_select.head(2)

Number of articles in selection: 41 (0.1% of total articles)
Examples:

,title,publisher,date,section,body,length,letters_flag,country_flag,foreign_countries,us_mentions,source_file,publisher_raw,section_clean,section_category
1782,Bridgeport mayor wins do-over election in race...,Other publisher,2024-02-28,NATION WORLD,Bridgeport Mayor Joe Ganim won a do-over elect...,1155,False,US_ONLY,[],"[Connecticut, New York]",Other publishers/Files (500) (2).DOCX,Dayton Daily News (Ohio),nation world,World/International
1992,South Dakota lawmakers see alignment with Noem...,Other publisher,2024-01-08,NATION WORLD,"Workforce needs, the budget and tax cuts will ...",857,False,US_ONLY,[],"[Nebraska, South Dakota, US]",Other publishers/Files (500) (2).DOCX,Dayton Daily News (Ohio),nation world,World/International

In [21]:
# domestic secondary categories, with US country flag mention
country_flag_selection = "FOREIGN_ONLY"

df_select = df_articles.loc[(df_articles['section_category'].isin(domestic_categories_secondary)) & (df_articles['country_flag'] == country_flag_selection)]
print(f"Number of articles in selection: {df_select.shape[0]} ({round(df_select.shape[0] / df_articles.shape[0] * 100, 2)}% of total articles)")

print("Examples:")
# examples
df_select.head(2)

Number of articles in selection: 1490 (3.62% of total articles)
Examples:

,title,publisher,date,section,body,length,letters_flag,country_flag,foreign_countries,us_mentions,source_file,publisher_raw,section_clean,section_category
8,"Crash, Burn, Repeat: A Pop Star's Spectacle",New York Times,2024-12-27,"Section C; Column 0; Movies, Performing Arts/W...","The singer Robbie Williams's caustic, often vu...",561,False,FOREIGN_ONLY,[London (Capital)],[],NYT/1.DOCX,The New York Times,"section c; column 0; movies, performing arts/w...",Arts/Culture
11,'Better Man' Review: The Boy in the Band; Crit...,New York Times,2024-12-25,MOVIES,"The singer Robbie Williams's caustic, often vu...",585,False,FOREIGN_ONLY,[London (Capital)],[],NYT/1.DOCX,The New York Times,movies,Arts/Culture

None for both:

In [22]:
section_category_selection = "None"
country_flag_selection = "NONE"

df_select = df_articles.loc[(df_articles['section_category'] == section_category_selection) & (df_articles['country_flag'] == country_flag_selection)]
print(f"Number of articles in selection: {df_select.shape[0]} ({round(df_select.shape[0] / df_articles.shape[0] * 100, 2)}% of total articles)")

print("Examples:")
# examples
df_select.head(2)

Number of articles in selection: 368 (0.89% of total articles)
Examples:

,title,publisher,date,section,body,length,letters_flag,country_flag,foreign_countries,us_mentions,source_file,publisher_raw,section_clean,section_category
146,RESTAURANT ANNIVERSARIES,Other publisher,2024-11-28,TASTE; Pg. 3T,"70\nyears\nIn 70 years, the only thing that's ...",334,False,NONE,[],[],Other publishers/Files (500) (1).DOCX,"Star Tribune (Minneapolis, MN)",taste; pg. 3t,None
226,"In ""˜Bird,' a gritty fairy tale doesn't take f...",Other publisher,2024-11-17,NEWS; Pg. 12,"""Is it too real for ya?"" blares in the backgro...",585,False,NONE,[],[],Other publishers/Files (500) (1).DOCX,Chicago Daily Herald,news; pg. 12,None